### ISSUE TITLE
Audit of Clarity Contracts

### ISSUE THREAD

**Issue by jose-compu** [LNSwap/lnstxbridge#36]
* https://github.com/LNSwap/lnstxbridge/blob/main/contracts/stxswap_v10.clar (fbe9779)[https://github.com/LNSwap/lnstxbridge/commit/fbe9779a6ede469ae99709f64d511318b845d254])
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern

* https://github.com/LNSwap/lnstxbridge/blob/main/contracts/sip10swap_v3.clar
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern
 
* https://github.com/LNSwap/lnstxbridge/blob/main/contracts/triggerswap_v6.clar
  * [x] Access control
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern

* https://github.com/LNSwap/lnstxbridge/blob/main/contracts/trustless-rewards.clar
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [ ] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern

**Comment by jo-tm** [comment]
**[stxswap_v10.clar](https://github.com/LNSwap/lnstxbridge/blob/main/contracts/stxswap_v10.clar)**

LOW IMPACT Unsafe external calls: STX transfer are considered external calls. This transfer seems properly implemented using some `as-contract` patttern, but because `as-contract` replaces both `tx-sender` AND `contract-caller` with the contract principal then this patter is not suitable for contract composition (see https://github.com/Trust-Machines/stacks-sbtc/issues/523). This does not seem to be a direct use case (DeFi Composition) of this swaps because we have external LN interaction so is unlikely and flagged as _low_. This problem is mitigated by some project by using a Wrapped STX and `ft-transfer` that is not affected by this problem.

```clarity
...
(unwrap-panic (stx-transfer? amount tx-sender (as-contract tx-sender)))
...
(try! (as-contract (stx-transfer? (get amount swap) tx-sender claimer)))
...
(try! (as-contract (stx-transfer? (get amount swap) tx-sender claimer)))
```

**Comment by jose-compu** [comment]
.

**Comment by jose-compu** [comment]
.

**Comment by jose-compu** [comment]
@pseudozach Reported 2 Low impact and 1 Informational security issues on `stxswap_v10.clar`

**Comment by jose-compu** [comment]
.
